//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package sliceofstruct

import (
	fmt "fmt"

	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	field "k8s.io/apimachinery/pkg/util/validation/field"
	testscheme "k8s.io/code-generator/cmd/validation-gen/testscheme"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *testscheme.Scheme) error {
	scheme.AddValidationFunc((*M)(nil), func(opCtx operation.Context, obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_M(opCtx, obj.(*M), safe.Cast[*M](oldObj), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	return nil
}

func Validate_M(opCtx operation.Context, obj, oldObj *M, fldPath *field.Path) (errs field.ErrorList) {
	// field M.TypeMeta has no validation

	// field M.M0
	errs = append(errs,
		func(obj, oldObj []S, fldPath *field.Path) (errs field.ErrorList) {
			if e := validate.MaxItems(opCtx, fldPath, obj, oldObj, 1); len(e) != 0 {
				errs = append(errs, e...)
				return // do not proceed
			}
			return
		}(obj.M0, safe.Field(oldObj, func(oldObj *M) []S { return oldObj.M0 }), fldPath.Child("m0"))...)

	// field M.M1
	errs = append(errs,
		func(obj, oldObj SSliceLimited, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, Validate_SSliceLimited(opCtx, obj, oldObj, fldPath)...)
			return
		}(obj.M1, safe.Field(oldObj, func(oldObj *M) SSliceLimited { return oldObj.M1 }), fldPath.Child("m1"))...)

	// field M.M2
	errs = append(errs,
		func(obj, oldObj SSlice, fldPath *field.Path) (errs field.ErrorList) {
			if e := validate.MaxItems(opCtx, fldPath, obj, oldObj, 1); len(e) != 0 {
				errs = append(errs, e...)
				return // do not proceed
			}
			return
		}(obj.M2, safe.Field(oldObj, func(oldObj *M) SSlice { return oldObj.M2 }), fldPath.Child("m2"))...)

	// field M.M3
	errs = append(errs,
		func(obj, oldObj SSliceLimited, fldPath *field.Path) (errs field.ErrorList) {
			if e := validate.MaxItems(opCtx, fldPath, obj, oldObj, 1); len(e) != 0 {
				errs = append(errs, e...)
				return // do not proceed
			}
			errs = append(errs, Validate_SSliceLimited(opCtx, obj, oldObj, fldPath)...)
			return
		}(obj.M3, safe.Field(oldObj, func(oldObj *M) SSliceLimited { return oldObj.M3 }), fldPath.Child("m3"))...)

	// field M.M4
	errs = append(errs,
		func(obj, oldObj []*S, fldPath *field.Path) (errs field.ErrorList) {
			if e := validate.MaxItems(opCtx, fldPath, obj, oldObj, 1); len(e) != 0 {
				errs = append(errs, e...)
				return // do not proceed
			}
			return
		}(obj.M4, safe.Field(oldObj, func(oldObj *M) []*S { return oldObj.M4 }), fldPath.Child("m4"))...)

	// field M.M5
	errs = append(errs,
		func(obj, oldObj SPtrSliceLimited, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, Validate_SPtrSliceLimited(opCtx, obj, oldObj, fldPath)...)
			return
		}(obj.M5, safe.Field(oldObj, func(oldObj *M) SPtrSliceLimited { return oldObj.M5 }), fldPath.Child("m5"))...)

	// field M.M6
	errs = append(errs,
		func(obj, oldObj SPtrSlice, fldPath *field.Path) (errs field.ErrorList) {
			if e := validate.MaxItems(opCtx, fldPath, obj, oldObj, 1); len(e) != 0 {
				errs = append(errs, e...)
				return // do not proceed
			}
			return
		}(obj.M6, safe.Field(oldObj, func(oldObj *M) SPtrSlice { return oldObj.M6 }), fldPath.Child("m6"))...)

	// field M.M7
	errs = append(errs,
		func(obj, oldObj SPtrSliceLimited, fldPath *field.Path) (errs field.ErrorList) {
			if e := validate.MaxItems(opCtx, fldPath, obj, oldObj, 1); len(e) != 0 {
				errs = append(errs, e...)
				return // do not proceed
			}
			errs = append(errs, Validate_SPtrSliceLimited(opCtx, obj, oldObj, fldPath)...)
			return
		}(obj.M7, safe.Field(oldObj, func(oldObj *M) SPtrSliceLimited { return oldObj.M7 }), fldPath.Child("m7"))...)

	return errs
}

func Validate_SPtrSliceLimited(opCtx operation.Context, obj, oldObj SPtrSliceLimited, fldPath *field.Path) (errs field.ErrorList) {
	// type SPtrSliceLimited
	if e := validate.MaxItems(opCtx, fldPath, obj, oldObj, 2); len(e) != 0 {
		errs = append(errs, e...)
		return // do not proceed
	}

	return errs
}

func Validate_SSliceLimited(opCtx operation.Context, obj, oldObj SSliceLimited, fldPath *field.Path) (errs field.ErrorList) {
	// type SSliceLimited
	if e := validate.MaxItems(opCtx, fldPath, obj, oldObj, 2); len(e) != 0 {
		errs = append(errs, e...)
		return // do not proceed
	}

	return errs
}
