//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package v1

import (
	fmt "fmt"

	v1 "k8s.io/api/core/v1"
	validate "k8s.io/apimachinery/pkg/api/validate"
	runtime "k8s.io/apimachinery/pkg/runtime"
	field "k8s.io/apimachinery/pkg/util/validation/field"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *runtime.Scheme) error {
	scheme.AddValidationFunc(new(v1.Binding), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_Binding(obj.(*v1.Binding), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.ComponentStatus), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_ComponentStatus(obj.(*v1.ComponentStatus), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.ComponentStatusList), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_ComponentStatusList(obj.(*v1.ComponentStatusList), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.ConfigMap), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_ConfigMap(obj.(*v1.ConfigMap), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.ConfigMapList), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_ConfigMapList(obj.(*v1.ConfigMapList), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.Endpoints), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_Endpoints(obj.(*v1.Endpoints), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.EndpointsList), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_EndpointsList(obj.(*v1.EndpointsList), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.Event), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_Event(obj.(*v1.Event), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.EventList), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_EventList(obj.(*v1.EventList), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.LimitRange), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_LimitRange(obj.(*v1.LimitRange), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.LimitRangeList), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_LimitRangeList(obj.(*v1.LimitRangeList), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.List), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_List(obj.(*v1.List), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.Namespace), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_Namespace(obj.(*v1.Namespace), nil)
		}
		if len(subresources) == 1 && subresources[0] == "status" {
			return nil // v1.NamespaceStatus has no validation
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.NamespaceList), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_NamespaceList(obj.(*v1.NamespaceList), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.Node), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_Node(obj.(*v1.Node), nil)
		}
		if len(subresources) == 1 && subresources[0] == "status" {
			return nil // v1.NodeStatus has no validation
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.NodeList), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_NodeList(obj.(*v1.NodeList), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.NodeProxyOptions), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_NodeProxyOptions(obj.(*v1.NodeProxyOptions), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.PersistentVolume), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_PersistentVolume(obj.(*v1.PersistentVolume), nil)
		}
		if len(subresources) == 1 && subresources[0] == "status" {
			return nil // v1.PersistentVolumeStatus has no validation
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.PersistentVolumeClaim), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_PersistentVolumeClaim(obj.(*v1.PersistentVolumeClaim), nil)
		}
		if len(subresources) == 1 && subresources[0] == "status" {
			return nil // v1.PersistentVolumeClaimStatus has no validation
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.PersistentVolumeClaimList), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_PersistentVolumeClaimList(obj.(*v1.PersistentVolumeClaimList), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.PersistentVolumeList), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_PersistentVolumeList(obj.(*v1.PersistentVolumeList), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.Pod), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_Pod(obj.(*v1.Pod), nil)
		}
		if len(subresources) == 1 && subresources[0] == "status" {
			root := obj.(*v1.Pod)
			return Validate_PodStatus(&root.Status, nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.PodAttachOptions), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_PodAttachOptions(obj.(*v1.PodAttachOptions), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.PodExecOptions), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_PodExecOptions(obj.(*v1.PodExecOptions), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.PodList), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_PodList(obj.(*v1.PodList), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.PodLogOptions), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_PodLogOptions(obj.(*v1.PodLogOptions), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.PodPortForwardOptions), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_PodPortForwardOptions(obj.(*v1.PodPortForwardOptions), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.PodProxyOptions), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_PodProxyOptions(obj.(*v1.PodProxyOptions), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.PodStatusResult), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_PodStatusResult(obj.(*v1.PodStatusResult), nil)
		}
		if len(subresources) == 1 && subresources[0] == "status" {
			root := obj.(*v1.PodStatusResult)
			return Validate_PodStatus(&root.Status, nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.PodTemplate), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_PodTemplate(obj.(*v1.PodTemplate), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.PodTemplateList), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_PodTemplateList(obj.(*v1.PodTemplateList), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.RangeAllocation), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_RangeAllocation(obj.(*v1.RangeAllocation), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.ReplicationController), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_ReplicationController(obj.(*v1.ReplicationController), nil)
		}
		if len(subresources) == 1 && subresources[0] == "status" {
			return nil // v1.ReplicationControllerStatus has no validation
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.ReplicationControllerList), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_ReplicationControllerList(obj.(*v1.ReplicationControllerList), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.ResourceQuota), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_ResourceQuota(obj.(*v1.ResourceQuota), nil)
		}
		if len(subresources) == 1 && subresources[0] == "status" {
			return nil // v1.ResourceQuotaStatus has no validation
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.ResourceQuotaList), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_ResourceQuotaList(obj.(*v1.ResourceQuotaList), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.Secret), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_Secret(obj.(*v1.Secret), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.SecretList), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_SecretList(obj.(*v1.SecretList), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.SerializedReference), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_SerializedReference(obj.(*v1.SerializedReference), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.Service), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_Service(obj.(*v1.Service), nil)
		}
		if len(subresources) == 1 && subresources[0] == "status" {
			return nil // v1.ServiceStatus has no validation
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.ServiceAccount), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_ServiceAccount(obj.(*v1.ServiceAccount), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.ServiceAccountList), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_ServiceAccountList(obj.(*v1.ServiceAccountList), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.ServiceList), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_ServiceList(obj.(*v1.ServiceList), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc(new(v1.ServiceProxyOptions), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_ServiceProxyOptions(obj.(*v1.ServiceProxyOptions), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	return nil
}

func Validate_Binding(obj *v1.Binding, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.Binding.TypeMeta has no validation
	// field v1.Binding.ObjectMeta has no validation
	// field v1.Binding.Target has no validation
	return errs
}

func Validate_ComponentStatus(obj *v1.ComponentStatus, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.ComponentStatus.TypeMeta has no validation
	// field v1.ComponentStatus.ObjectMeta has no validation
	// field v1.ComponentStatus.Conditions has no validation
	return errs
}

func Validate_ComponentStatusList(obj *v1.ComponentStatusList, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.ComponentStatusList.TypeMeta has no validation
	// field v1.ComponentStatusList.ListMeta has no validation
	// field v1.ComponentStatusList.Items has no validation
	return errs
}

func Validate_ConfigMap(obj *v1.ConfigMap, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.ConfigMap.TypeMeta has no validation
	// field v1.ConfigMap.ObjectMeta has no validation
	// field v1.ConfigMap.Immutable has no validation
	// field v1.ConfigMap.Data has no validation
	// field v1.ConfigMap.BinaryData has no validation
	return errs
}

func Validate_ConfigMapList(obj *v1.ConfigMapList, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.ConfigMapList.TypeMeta has no validation
	// field v1.ConfigMapList.ListMeta has no validation
	// field v1.ConfigMapList.Items has no validation
	return errs
}

func Validate_ContainerStatus(obj *v1.ContainerStatus, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.ContainerStatus.Name has no validation
	// field v1.ContainerStatus.State has no validation
	// field v1.ContainerStatus.LastTerminationState has no validation
	// field v1.ContainerStatus.Ready has no validation
	// field v1.ContainerStatus.RestartCount has no validation
	// field v1.ContainerStatus.Image has no validation
	// field v1.ContainerStatus.ImageID has no validation
	// field v1.ContainerStatus.ContainerID has no validation
	// field v1.ContainerStatus.Started has no validation
	// field v1.ContainerStatus.AllocatedResources has no validation
	// field v1.ContainerStatus.Resources has no validation
	// field v1.ContainerStatus.VolumeMounts has no validation
	// field v1.ContainerStatus.User has no validation

	// field v1.ContainerStatus.AllocatedResourcesStatus
	errs = append(errs,
		func(obj []v1.ResourceStatus, fldPath *field.Path) (errs field.ErrorList) {
			for i, val := range obj {
				errs = append(errs,
					func(obj v1.ResourceStatus, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, Validate_ResourceStatus(&obj, fldPath)...)
						return
					}(val, fldPath.Index(i))...)
			}
			return
		}(obj.AllocatedResourcesStatus, fldPath.Child("allocatedResourcesStatus"))...)

	return errs
}

func Validate_Endpoints(obj *v1.Endpoints, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.Endpoints.TypeMeta has no validation
	// field v1.Endpoints.ObjectMeta has no validation
	// field v1.Endpoints.Subsets has no validation
	return errs
}

func Validate_EndpointsList(obj *v1.EndpointsList, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.EndpointsList.TypeMeta has no validation
	// field v1.EndpointsList.ListMeta has no validation
	// field v1.EndpointsList.Items has no validation
	return errs
}

func Validate_Event(obj *v1.Event, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.Event.TypeMeta has no validation
	// field v1.Event.ObjectMeta has no validation
	// field v1.Event.InvolvedObject has no validation
	// field v1.Event.Reason has no validation
	// field v1.Event.Message has no validation
	// field v1.Event.Source has no validation
	// field v1.Event.FirstTimestamp has no validation
	// field v1.Event.LastTimestamp has no validation
	// field v1.Event.Count has no validation
	// field v1.Event.Type has no validation
	// field v1.Event.EventTime has no validation
	// field v1.Event.Series has no validation
	// field v1.Event.Action has no validation
	// field v1.Event.Related has no validation
	// field v1.Event.ReportingController has no validation
	// field v1.Event.ReportingInstance has no validation
	return errs
}

func Validate_EventList(obj *v1.EventList, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.EventList.TypeMeta has no validation
	// field v1.EventList.ListMeta has no validation
	// field v1.EventList.Items has no validation
	return errs
}

func Validate_HostAlias(obj *v1.HostAlias, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.HostAlias.IP
	errs = append(errs,
		func(obj string, fldPath *field.Path) (errs field.ErrorList) {
			if e := validate.Required(fldPath, obj); len(e) != 0 {
				errs = append(errs, e...)
				return // fatal
			}
			return
		}(obj.IP, fldPath.Child("ip"))...)

	// field v1.HostAlias.Hostnames has no validation
	return errs
}

func Validate_HostIP(obj *v1.HostIP, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.HostIP.IP
	errs = append(errs,
		func(obj string, fldPath *field.Path) (errs field.ErrorList) {
			if e := validate.Required(fldPath, obj); len(e) != 0 {
				errs = append(errs, e...)
				return // fatal
			}
			return
		}(obj.IP, fldPath.Child("ip"))...)

	return errs
}

func Validate_LimitRange(obj *v1.LimitRange, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.LimitRange.TypeMeta has no validation
	// field v1.LimitRange.ObjectMeta has no validation
	// field v1.LimitRange.Spec has no validation
	return errs
}

func Validate_LimitRangeList(obj *v1.LimitRangeList, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.LimitRangeList.TypeMeta has no validation
	// field v1.LimitRangeList.ListMeta has no validation
	// field v1.LimitRangeList.Items has no validation
	return errs
}

func Validate_List(obj *v1.List, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.List.TypeMeta has no validation
	// field v1.List.ListMeta has no validation
	// field v1.List.Items has no validation
	return errs
}

func Validate_Namespace(obj *v1.Namespace, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.Namespace.TypeMeta has no validation
	// field v1.Namespace.ObjectMeta has no validation
	// field v1.Namespace.Spec has no validation
	// field v1.Namespace.Status has no validation
	return errs
}

func Validate_NamespaceList(obj *v1.NamespaceList, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.NamespaceList.TypeMeta has no validation
	// field v1.NamespaceList.ListMeta has no validation
	// field v1.NamespaceList.Items has no validation
	return errs
}

func Validate_Node(obj *v1.Node, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.Node.TypeMeta has no validation
	// field v1.Node.ObjectMeta has no validation
	// field v1.Node.Spec has no validation
	// field v1.Node.Status has no validation
	return errs
}

func Validate_NodeList(obj *v1.NodeList, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.NodeList.TypeMeta has no validation
	// field v1.NodeList.ListMeta has no validation
	// field v1.NodeList.Items has no validation
	return errs
}

func Validate_NodeProxyOptions(obj *v1.NodeProxyOptions, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.NodeProxyOptions.TypeMeta has no validation
	// field v1.NodeProxyOptions.Path has no validation
	return errs
}

func Validate_PersistentVolume(obj *v1.PersistentVolume, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.PersistentVolume.TypeMeta has no validation
	// field v1.PersistentVolume.ObjectMeta has no validation
	// field v1.PersistentVolume.Spec has no validation
	// field v1.PersistentVolume.Status has no validation
	return errs
}

func Validate_PersistentVolumeClaim(obj *v1.PersistentVolumeClaim, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.PersistentVolumeClaim.TypeMeta has no validation
	// field v1.PersistentVolumeClaim.ObjectMeta has no validation
	// field v1.PersistentVolumeClaim.Spec has no validation
	// field v1.PersistentVolumeClaim.Status has no validation
	return errs
}

func Validate_PersistentVolumeClaimList(obj *v1.PersistentVolumeClaimList, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.PersistentVolumeClaimList.TypeMeta has no validation
	// field v1.PersistentVolumeClaimList.ListMeta has no validation
	// field v1.PersistentVolumeClaimList.Items has no validation
	return errs
}

func Validate_PersistentVolumeList(obj *v1.PersistentVolumeList, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.PersistentVolumeList.TypeMeta has no validation
	// field v1.PersistentVolumeList.ListMeta has no validation
	// field v1.PersistentVolumeList.Items has no validation
	return errs
}

func Validate_Pod(obj *v1.Pod, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.Pod.TypeMeta has no validation
	// field v1.Pod.ObjectMeta has no validation

	// field v1.Pod.Spec
	errs = append(errs,
		func(obj v1.PodSpec, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, Validate_PodSpec(&obj, fldPath)...)
			return
		}(obj.Spec, fldPath.Child("spec"))...)

	// field v1.Pod.Status
	errs = append(errs,
		func(obj v1.PodStatus, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, Validate_PodStatus(&obj, fldPath)...)
			return
		}(obj.Status, fldPath.Child("status"))...)

	return errs
}

func Validate_PodAttachOptions(obj *v1.PodAttachOptions, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.PodAttachOptions.TypeMeta has no validation
	// field v1.PodAttachOptions.Stdin has no validation
	// field v1.PodAttachOptions.Stdout has no validation
	// field v1.PodAttachOptions.Stderr has no validation
	// field v1.PodAttachOptions.TTY has no validation
	// field v1.PodAttachOptions.Container has no validation
	return errs
}

func Validate_PodExecOptions(obj *v1.PodExecOptions, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.PodExecOptions.TypeMeta has no validation
	// field v1.PodExecOptions.Stdin has no validation
	// field v1.PodExecOptions.Stdout has no validation
	// field v1.PodExecOptions.Stderr has no validation
	// field v1.PodExecOptions.TTY has no validation
	// field v1.PodExecOptions.Container has no validation
	// field v1.PodExecOptions.Command has no validation
	return errs
}

func Validate_PodIP(obj *v1.PodIP, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.PodIP.IP
	errs = append(errs,
		func(obj string, fldPath *field.Path) (errs field.ErrorList) {
			if e := validate.Required(fldPath, obj); len(e) != 0 {
				errs = append(errs, e...)
				return // fatal
			}
			return
		}(obj.IP, fldPath.Child("ip"))...)

	return errs
}

func Validate_PodList(obj *v1.PodList, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.PodList.TypeMeta has no validation
	// field v1.PodList.ListMeta has no validation

	// field v1.PodList.Items
	errs = append(errs,
		func(obj []v1.Pod, fldPath *field.Path) (errs field.ErrorList) {
			for i, val := range obj {
				errs = append(errs,
					func(obj v1.Pod, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, Validate_Pod(&obj, fldPath)...)
						return
					}(val, fldPath.Index(i))...)
			}
			return
		}(obj.Items, fldPath.Child("items"))...)

	return errs
}

func Validate_PodLogOptions(obj *v1.PodLogOptions, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.PodLogOptions.TypeMeta has no validation
	// field v1.PodLogOptions.Container has no validation
	// field v1.PodLogOptions.Follow has no validation
	// field v1.PodLogOptions.Previous has no validation
	// field v1.PodLogOptions.SinceSeconds has no validation
	// field v1.PodLogOptions.SinceTime has no validation
	// field v1.PodLogOptions.Timestamps has no validation
	// field v1.PodLogOptions.TailLines has no validation
	// field v1.PodLogOptions.LimitBytes has no validation
	// field v1.PodLogOptions.InsecureSkipTLSVerifyBackend has no validation
	return errs
}

func Validate_PodPortForwardOptions(obj *v1.PodPortForwardOptions, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.PodPortForwardOptions.TypeMeta has no validation
	// field v1.PodPortForwardOptions.Ports has no validation
	return errs
}

func Validate_PodProxyOptions(obj *v1.PodProxyOptions, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.PodProxyOptions.TypeMeta has no validation
	// field v1.PodProxyOptions.Path has no validation
	return errs
}

func Validate_PodSpec(obj *v1.PodSpec, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.PodSpec.Volumes
	errs = append(errs,
		func(obj []v1.Volume, fldPath *field.Path) (errs field.ErrorList) {
			for i, val := range obj {
				errs = append(errs,
					func(obj v1.Volume, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, Validate_Volume(&obj, fldPath)...)
						return
					}(val, fldPath.Index(i))...)
			}
			return
		}(obj.Volumes, fldPath.Child("volumes"))...)

	// field v1.PodSpec.InitContainers has no validation
	// field v1.PodSpec.Containers has no validation
	// field v1.PodSpec.EphemeralContainers has no validation
	// field v1.PodSpec.RestartPolicy has no validation
	// field v1.PodSpec.TerminationGracePeriodSeconds has no validation
	// field v1.PodSpec.ActiveDeadlineSeconds has no validation
	// field v1.PodSpec.DNSPolicy has no validation
	// field v1.PodSpec.NodeSelector has no validation
	// field v1.PodSpec.ServiceAccountName has no validation
	// field v1.PodSpec.DeprecatedServiceAccount has no validation
	// field v1.PodSpec.AutomountServiceAccountToken has no validation
	// field v1.PodSpec.NodeName has no validation
	// field v1.PodSpec.HostNetwork has no validation
	// field v1.PodSpec.HostPID has no validation
	// field v1.PodSpec.HostIPC has no validation
	// field v1.PodSpec.ShareProcessNamespace has no validation
	// field v1.PodSpec.SecurityContext has no validation
	// field v1.PodSpec.ImagePullSecrets has no validation
	// field v1.PodSpec.Hostname has no validation
	// field v1.PodSpec.Subdomain has no validation
	// field v1.PodSpec.Affinity has no validation
	// field v1.PodSpec.SchedulerName has no validation
	// field v1.PodSpec.Tolerations has no validation

	// field v1.PodSpec.HostAliases
	errs = append(errs,
		func(obj []v1.HostAlias, fldPath *field.Path) (errs field.ErrorList) {
			for i, val := range obj {
				errs = append(errs,
					func(obj v1.HostAlias, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, Validate_HostAlias(&obj, fldPath)...)
						return
					}(val, fldPath.Index(i))...)
			}
			return
		}(obj.HostAliases, fldPath.Child("hostAliases"))...)

	// field v1.PodSpec.PriorityClassName has no validation
	// field v1.PodSpec.Priority has no validation
	// field v1.PodSpec.DNSConfig has no validation
	// field v1.PodSpec.ReadinessGates has no validation
	// field v1.PodSpec.RuntimeClassName has no validation
	// field v1.PodSpec.EnableServiceLinks has no validation
	// field v1.PodSpec.PreemptionPolicy has no validation
	// field v1.PodSpec.Overhead has no validation
	// field v1.PodSpec.TopologySpreadConstraints has no validation
	// field v1.PodSpec.SetHostnameAsFQDN has no validation
	// field v1.PodSpec.OS has no validation
	// field v1.PodSpec.HostUsers has no validation
	// field v1.PodSpec.SchedulingGates has no validation
	// field v1.PodSpec.ResourceClaims has no validation
	return errs
}

func Validate_PodStatus(obj *v1.PodStatus, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.PodStatus.Phase has no validation
	// field v1.PodStatus.Conditions has no validation
	// field v1.PodStatus.Message has no validation
	// field v1.PodStatus.Reason has no validation
	// field v1.PodStatus.NominatedNodeName has no validation
	// field v1.PodStatus.HostIP has no validation

	// field v1.PodStatus.HostIPs
	errs = append(errs,
		func(obj []v1.HostIP, fldPath *field.Path) (errs field.ErrorList) {
			for i, val := range obj {
				errs = append(errs,
					func(obj v1.HostIP, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, Validate_HostIP(&obj, fldPath)...)
						return
					}(val, fldPath.Index(i))...)
			}
			return
		}(obj.HostIPs, fldPath.Child("hostIPs"))...)

	// field v1.PodStatus.PodIP has no validation

	// field v1.PodStatus.PodIPs
	errs = append(errs,
		func(obj []v1.PodIP, fldPath *field.Path) (errs field.ErrorList) {
			for i, val := range obj {
				errs = append(errs,
					func(obj v1.PodIP, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, Validate_PodIP(&obj, fldPath)...)
						return
					}(val, fldPath.Index(i))...)
			}
			return
		}(obj.PodIPs, fldPath.Child("podIPs"))...)

	// field v1.PodStatus.StartTime has no validation

	// field v1.PodStatus.InitContainerStatuses
	errs = append(errs,
		func(obj []v1.ContainerStatus, fldPath *field.Path) (errs field.ErrorList) {
			for i, val := range obj {
				errs = append(errs,
					func(obj v1.ContainerStatus, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, Validate_ContainerStatus(&obj, fldPath)...)
						return
					}(val, fldPath.Index(i))...)
			}
			return
		}(obj.InitContainerStatuses, fldPath.Child("initContainerStatuses"))...)

	// field v1.PodStatus.ContainerStatuses
	errs = append(errs,
		func(obj []v1.ContainerStatus, fldPath *field.Path) (errs field.ErrorList) {
			for i, val := range obj {
				errs = append(errs,
					func(obj v1.ContainerStatus, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, Validate_ContainerStatus(&obj, fldPath)...)
						return
					}(val, fldPath.Index(i))...)
			}
			return
		}(obj.ContainerStatuses, fldPath.Child("containerStatuses"))...)

	// field v1.PodStatus.QOSClass has no validation

	// field v1.PodStatus.EphemeralContainerStatuses
	errs = append(errs,
		func(obj []v1.ContainerStatus, fldPath *field.Path) (errs field.ErrorList) {
			for i, val := range obj {
				errs = append(errs,
					func(obj v1.ContainerStatus, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, Validate_ContainerStatus(&obj, fldPath)...)
						return
					}(val, fldPath.Index(i))...)
			}
			return
		}(obj.EphemeralContainerStatuses, fldPath.Child("ephemeralContainerStatuses"))...)

	// field v1.PodStatus.Resize has no validation
	// field v1.PodStatus.ResourceClaimStatuses has no validation
	return errs
}

func Validate_PodStatusResult(obj *v1.PodStatusResult, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.PodStatusResult.TypeMeta has no validation
	// field v1.PodStatusResult.ObjectMeta has no validation

	// field v1.PodStatusResult.Status
	errs = append(errs,
		func(obj v1.PodStatus, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, Validate_PodStatus(&obj, fldPath)...)
			return
		}(obj.Status, fldPath.Child("status"))...)

	return errs
}

func Validate_PodTemplate(obj *v1.PodTemplate, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.PodTemplate.TypeMeta has no validation
	// field v1.PodTemplate.ObjectMeta has no validation

	// field v1.PodTemplate.Template
	errs = append(errs,
		func(obj v1.PodTemplateSpec, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, Validate_PodTemplateSpec(&obj, fldPath)...)
			return
		}(obj.Template, fldPath.Child("template"))...)

	return errs
}

func Validate_PodTemplateList(obj *v1.PodTemplateList, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.PodTemplateList.TypeMeta has no validation
	// field v1.PodTemplateList.ListMeta has no validation

	// field v1.PodTemplateList.Items
	errs = append(errs,
		func(obj []v1.PodTemplate, fldPath *field.Path) (errs field.ErrorList) {
			for i, val := range obj {
				errs = append(errs,
					func(obj v1.PodTemplate, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, Validate_PodTemplate(&obj, fldPath)...)
						return
					}(val, fldPath.Index(i))...)
			}
			return
		}(obj.Items, fldPath.Child("items"))...)

	return errs
}

func Validate_PodTemplateSpec(obj *v1.PodTemplateSpec, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.PodTemplateSpec.ObjectMeta has no validation

	// field v1.PodTemplateSpec.Spec
	errs = append(errs,
		func(obj v1.PodSpec, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, Validate_PodSpec(&obj, fldPath)...)
			return
		}(obj.Spec, fldPath.Child("spec"))...)

	return errs
}

func Validate_RangeAllocation(obj *v1.RangeAllocation, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.RangeAllocation.TypeMeta has no validation
	// field v1.RangeAllocation.ObjectMeta has no validation
	// field v1.RangeAllocation.Range has no validation
	// field v1.RangeAllocation.Data has no validation
	return errs
}

func Validate_ReplicationController(obj *v1.ReplicationController, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.ReplicationController.TypeMeta has no validation
	// field v1.ReplicationController.ObjectMeta has no validation

	// field v1.ReplicationController.Spec
	errs = append(errs,
		func(obj v1.ReplicationControllerSpec, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, Validate_ReplicationControllerSpec(&obj, fldPath)...)
			return
		}(obj.Spec, fldPath.Child("spec"))...)

	// field v1.ReplicationController.Status has no validation
	return errs
}

func Validate_ReplicationControllerList(obj *v1.ReplicationControllerList, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.ReplicationControllerList.TypeMeta has no validation
	// field v1.ReplicationControllerList.ListMeta has no validation

	// field v1.ReplicationControllerList.Items
	errs = append(errs,
		func(obj []v1.ReplicationController, fldPath *field.Path) (errs field.ErrorList) {
			for i, val := range obj {
				errs = append(errs,
					func(obj v1.ReplicationController, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, Validate_ReplicationController(&obj, fldPath)...)
						return
					}(val, fldPath.Index(i))...)
			}
			return
		}(obj.Items, fldPath.Child("items"))...)

	return errs
}

func Validate_ReplicationControllerSpec(obj *v1.ReplicationControllerSpec, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.ReplicationControllerSpec.Replicas has no validation
	// field v1.ReplicationControllerSpec.MinReadySeconds has no validation
	// field v1.ReplicationControllerSpec.Selector has no validation

	// field v1.ReplicationControllerSpec.Template
	errs = append(errs,
		func(obj *v1.PodTemplateSpec, fldPath *field.Path) (errs field.ErrorList) {
			if obj != nil {
				errs = append(errs, Validate_PodTemplateSpec(obj, fldPath)...)
			}
			return
		}(obj.Template, fldPath.Child("template"))...)

	return errs
}

func Validate_ResourceQuota(obj *v1.ResourceQuota, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.ResourceQuota.TypeMeta has no validation
	// field v1.ResourceQuota.ObjectMeta has no validation
	// field v1.ResourceQuota.Spec has no validation
	// field v1.ResourceQuota.Status has no validation
	return errs
}

func Validate_ResourceQuotaList(obj *v1.ResourceQuotaList, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.ResourceQuotaList.TypeMeta has no validation
	// field v1.ResourceQuotaList.ListMeta has no validation
	// field v1.ResourceQuotaList.Items has no validation
	return errs
}

func Validate_ResourceStatus(obj *v1.ResourceStatus, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.ResourceStatus.Name
	errs = append(errs,
		func(obj v1.ResourceName, fldPath *field.Path) (errs field.ErrorList) {
			if e := validate.Required(fldPath, obj); len(e) != 0 {
				errs = append(errs, e...)
				return // fatal
			}
			return
		}(obj.Name, fldPath.Child("name"))...)

	// field v1.ResourceStatus.Resources has no validation
	return errs
}

func Validate_Secret(obj *v1.Secret, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.Secret.TypeMeta has no validation
	// field v1.Secret.ObjectMeta has no validation
	// field v1.Secret.Immutable has no validation
	// field v1.Secret.Data has no validation
	// field v1.Secret.StringData has no validation
	// field v1.Secret.Type has no validation
	return errs
}

func Validate_SecretList(obj *v1.SecretList, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.SecretList.TypeMeta has no validation
	// field v1.SecretList.ListMeta has no validation
	// field v1.SecretList.Items has no validation
	return errs
}

func Validate_SerializedReference(obj *v1.SerializedReference, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.SerializedReference.TypeMeta has no validation
	// field v1.SerializedReference.Reference has no validation
	return errs
}

func Validate_Service(obj *v1.Service, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.Service.TypeMeta has no validation
	// field v1.Service.ObjectMeta has no validation
	// field v1.Service.Spec has no validation
	// field v1.Service.Status has no validation
	return errs
}

func Validate_ServiceAccount(obj *v1.ServiceAccount, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.ServiceAccount.TypeMeta has no validation
	// field v1.ServiceAccount.ObjectMeta has no validation
	// field v1.ServiceAccount.Secrets has no validation
	// field v1.ServiceAccount.ImagePullSecrets has no validation
	// field v1.ServiceAccount.AutomountServiceAccountToken has no validation
	return errs
}

func Validate_ServiceAccountList(obj *v1.ServiceAccountList, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.ServiceAccountList.TypeMeta has no validation
	// field v1.ServiceAccountList.ListMeta has no validation
	// field v1.ServiceAccountList.Items has no validation
	return errs
}

func Validate_ServiceList(obj *v1.ServiceList, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.ServiceList.TypeMeta has no validation
	// field v1.ServiceList.ListMeta has no validation
	// field v1.ServiceList.Items has no validation
	return errs
}

func Validate_ServiceProxyOptions(obj *v1.ServiceProxyOptions, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.ServiceProxyOptions.TypeMeta has no validation
	// field v1.ServiceProxyOptions.Path has no validation
	return errs
}

func Validate_Volume(obj *v1.Volume, fldPath *field.Path) (errs field.ErrorList) {
	// field v1.Volume.Name
	errs = append(errs,
		func(obj string, fldPath *field.Path) (errs field.ErrorList) {
			if e := validate.Required(fldPath, obj); len(e) != 0 {
				errs = append(errs, e...)
				return // fatal
			}
			errs = append(errs, validate.DNSLabel(fldPath, obj)...)
			return
		}(obj.Name, fldPath.Child("name"))...)

	// field v1.Volume.VolumeSource has no validation
	return errs
}
