//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package pointers

import (
	fmt "fmt"

	validate "k8s.io/apimachinery/pkg/api/validate"
	runtime "k8s.io/apimachinery/pkg/runtime"
	field "k8s.io/apimachinery/pkg/util/validation/field"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *runtime.Scheme) error {
	scheme.AddValidationFunc(new(T1), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_T1(obj.(*T1), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	return nil
}

func Validate_T1(in *T1, fldPath *field.Path) (errs field.ErrorList) {
	// TypeMeta

	// PS
	if in.PS != nil {
		errs = append(errs, validate.FixedResult(fldPath.Child("ps"), *in.PS, true, "field T1.PS")...)
	}

	// PI
	if in.PI != nil {
		errs = append(errs, validate.FixedResult(fldPath.Child("pi"), *in.PI, true, "field T1.PI")...)
	}

	// PB
	if in.PB != nil {
		errs = append(errs, validate.FixedResult(fldPath.Child("pb"), *in.PB, true, "field T1.PB")...)
	}

	// PF
	if in.PF != nil {
		errs = append(errs, validate.FixedResult(fldPath.Child("pf"), *in.PF, true, "field T1.PF")...)
	}

	// PT2
	if in.PT2 != nil {
		errs = append(errs, validate.FixedResult(fldPath.Child("pt2"), *in.PT2, true, "field T1.PT2")...)
	}
	if in.PT2 != nil {
		errs = append(errs, Validate_T2(in.PT2, fldPath.Child("pt2"))...)
	}

	// AnotherPS

	// AnotherPI

	// AnotherPB

	// AnotherPF

	// AnotherPT2
	if in.AnotherPT2 != nil {
		errs = append(errs, Validate_T2(in.AnotherPT2, fldPath.Child("aotherpt2"))...)
	}

	return errs
}

func Validate_T2(in *T2, fldPath *field.Path) (errs field.ErrorList) {
	// PS
	if in.PS != nil {
		errs = append(errs, validate.FixedResult(fldPath.Child("ps"), *in.PS, true, "field T2.PS")...)
	}

	// PI
	if in.PI != nil {
		errs = append(errs, validate.FixedResult(fldPath.Child("pi"), *in.PI, true, "field T2.PI")...)
	}

	// PB
	if in.PB != nil {
		errs = append(errs, validate.FixedResult(fldPath.Child("pb"), *in.PB, true, "field T2.PB")...)
	}

	// PF
	if in.PF != nil {
		errs = append(errs, validate.FixedResult(fldPath.Child("pf"), *in.PF, true, "field T2.PF")...)
	}

	return errs
}
