//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package maps

import (
	fmt "fmt"

	validate "k8s.io/apimachinery/pkg/api/validate"
	runtime "k8s.io/apimachinery/pkg/runtime"
	field "k8s.io/apimachinery/pkg/util/validation/field"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *runtime.Scheme) error {
	scheme.AddValidationFunc(new(T1), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_T1(obj.(*T1), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("No validation found for %T, subresources: %v", obj, subresources))}
	})
	return nil
}

func Validate_E1(in *E1, fldPath *field.Path) (errs field.ErrorList) {
	errs = append(errs, validate.FixedResult(fldPath, in, true, "type E1")...)
	return errs
}

func Validate_T1(in *T1, fldPath *field.Path) (errs field.ErrorList) {
	errs = append(errs, validate.FixedResult(fldPath, in, true, "type T1")...)
	// TypeMeta

	// MSS
	errs = append(errs, validate.FixedResult(fldPath.Child("mss"), in.MSS, true, "field T1.MSS")...)
	for key, val := range in.MSS {
	}

	// MSPS
	errs = append(errs, validate.FixedResult(fldPath.Child("msps"), in.MSPS, true, "field T1.MSPS")...)
	for key, val := range in.MSPS {
	}

	// MPSS
	errs = append(errs, validate.FixedResult(fldPath.Child("mpss"), in.MPSS, true, "field T1.MPSS")...)
	for key, val := range in.MPSS {
	}

	// MPSPS
	errs = append(errs, validate.FixedResult(fldPath.Child("mpsps"), in.MPSPS, true, "field T1.MPSPS")...)
	for key, val := range in.MPSPS {
	}

	// MST2
	errs = append(errs, validate.FixedResult(fldPath.Child("mst2"), in.MST2, true, "field T1.MST2")...)
	for key, val := range in.MST2 {
	}

	// MSPT2
	errs = append(errs, validate.FixedResult(fldPath.Child("mspt2"), in.MSPT2, true, "field T1.MSPT2")...)
	for key, val := range in.MSPT2 {
	}

	// MSE1
	errs = append(errs, validate.FixedResult(fldPath.Child("mse1"), in.MSE1, true, "field T1.MSE1")...)
	for key, val := range in.MSE1 {
		errs = append(errs, Validate_E1(&val, fldPath.Key(key))...)
	}

	// ME1S
	errs = append(errs, validate.FixedResult(fldPath.Child("<unknown-json-name>"), in.ME1S, true, "field T1.ME1S")...)
	for key, val := range in.ME1S {
		errs = append(errs, Validate_E1(&key, fldPath)...)
	}

	return errs
}
