//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package maps

import (
	fmt "fmt"

	validate "k8s.io/apimachinery/pkg/api/validate"
	runtime "k8s.io/apimachinery/pkg/runtime"
	field "k8s.io/apimachinery/pkg/util/validation/field"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *runtime.Scheme) error {
	scheme.AddValidationFunc(new(T1), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_T1(obj.(*T1), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	return nil
}

func Validate_E1(obj *E1, fldPath *field.Path) (errs field.ErrorList) {
	// type E1
	if obj != nil {
		errs = append(errs, validate.FixedResult(fldPath, *obj, true, "type E1")...)
	}

	return errs
}

func Validate_T1(obj *T1, fldPath *field.Path) (errs field.ErrorList) {
	// field T1.TypeMeta has no validation

	// field T1.MSS
	errs = append(errs,
		func(obj map[string]string, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T1.MSS")...)
			for key, val := range obj {
				errs = append(errs,
					func(obj string, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, validate.FixedResult(fldPath, obj, true, "key T1.MSS[*]")...)
						return
					}(key, fldPath)...)
				errs = append(errs,
					func(obj string, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, validate.FixedResult(fldPath, obj, true, "val T1.MSS[*]")...)
						return
					}(val, fldPath.Key(key))...)
			}
			return
		}(obj.MSS, fldPath.Child("mss"))...)

	// field T1.MSPS
	errs = append(errs,
		func(obj map[string]*string, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T1.MSPS")...)
			for key, val := range obj {
				errs = append(errs,
					func(obj string, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, validate.FixedResult(fldPath, obj, true, "key T1.MSPS[*]")...)
						return
					}(key, fldPath)...)
				errs = append(errs,
					func(obj *string, fldPath *field.Path) (errs field.ErrorList) {
						if obj != nil {
							errs = append(errs, validate.FixedResult(fldPath, *obj, true, "val T1.MSPS[*]")...)
						}
						return
					}(val, fldPath.Key(key))...)
			}
			return
		}(obj.MSPS, fldPath.Child("msps"))...)

	// field T1.MPSS
	errs = append(errs,
		func(obj map[*string]string, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T1.MPSS")...)
			for key, val := range obj {
				errs = append(errs,
					func(obj *string, fldPath *field.Path) (errs field.ErrorList) {
						if obj != nil {
							errs = append(errs, validate.FixedResult(fldPath, *obj, true, "key T1.MPSS[*]")...)
						}
						return
					}(key, fldPath)...)
				errs = append(errs,
					func(obj string, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, validate.FixedResult(fldPath, obj, true, "val T1.MPSS[*]")...)
						return
					}(val, fldPath.Key(key))...)
			}
			return
		}(obj.MPSS, fldPath.Child("mpss"))...)

	// field T1.MPSPS
	errs = append(errs,
		func(obj map[*string]*string, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T1.MPSPS")...)
			for key, val := range obj {
				errs = append(errs,
					func(obj *string, fldPath *field.Path) (errs field.ErrorList) {
						if obj != nil {
							errs = append(errs, validate.FixedResult(fldPath, *obj, true, "key T1.MPSPS[*]")...)
						}
						return
					}(key, fldPath)...)
				errs = append(errs,
					func(obj *string, fldPath *field.Path) (errs field.ErrorList) {
						if obj != nil {
							errs = append(errs, validate.FixedResult(fldPath, *obj, true, "val T1.MPSPS[*]")...)
						}
						return
					}(val, fldPath.Key(key))...)
			}
			return
		}(obj.MPSPS, fldPath.Child("mpsps"))...)

	// field T1.MST2
	errs = append(errs,
		func(obj map[string]string, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T1.MST2")...)
			for key, val := range obj {
				errs = append(errs,
					func(obj string, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, validate.FixedResult(fldPath, obj, true, "key T1.MST2[*]")...)
						return
					}(key, fldPath)...)
				errs = append(errs,
					func(obj string, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, validate.FixedResult(fldPath, obj, true, "val T1.MST2[*]")...)
						return
					}(val, fldPath.Key(key))...)
			}
			return
		}(obj.MST2, fldPath.Child("mst2"))...)

	// field T1.MSPT2
	errs = append(errs,
		func(obj map[string]*string, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T1.MSPT2")...)
			for key, val := range obj {
				errs = append(errs,
					func(obj string, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, validate.FixedResult(fldPath, obj, true, "key T1.MSPT2[*]")...)
						return
					}(key, fldPath)...)
				errs = append(errs,
					func(obj *string, fldPath *field.Path) (errs field.ErrorList) {
						if obj != nil {
							errs = append(errs, validate.FixedResult(fldPath, *obj, true, "val T1.MSPT2[*]")...)
						}
						return
					}(val, fldPath.Key(key))...)
			}
			return
		}(obj.MSPT2, fldPath.Child("mspt2"))...)

	// field T1.MSE1
	errs = append(errs,
		func(obj map[string]E1, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T1.MSE1")...)
			for key, val := range obj {
				errs = append(errs,
					func(obj string, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, validate.FixedResult(fldPath, obj, true, "key T1.MSE1[*]")...)
						return
					}(key, fldPath)...)
				errs = append(errs,
					func(obj E1, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, validate.FixedResult(fldPath, obj, true, "val T1.MSE1[*]")...)
						errs = append(errs, Validate_E1(&obj, fldPath)...)
						return
					}(val, fldPath.Key(key))...)
			}
			return
		}(obj.MSE1, fldPath.Child("mse1"))...)

	// field T1.ME1S
	errs = append(errs,
		func(obj map[E1]string, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T1.ME1S")...)
			for key, val := range obj {
				errs = append(errs,
					func(obj E1, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, validate.FixedResult(fldPath, obj, true, "key T1.ME1S[*]")...)
						errs = append(errs, Validate_E1(&obj, fldPath)...)
						return
					}(key, fldPath)...)
				errs = append(errs,
					func(obj string, fldPath *field.Path) (errs field.ErrorList) {
						errs = append(errs, validate.FixedResult(fldPath, obj, true, "val T1.ME1S[*]")...)
						return
					}(val, fldPath.Key(key))...)
			}
			return
		}(obj.ME1S, fldPath.Child("me1s"))...)

	// field T1.AnotherMSS has no validation
	// field T1.AnotherMSPS has no validation
	// field T1.AnotherMPSS has no validation
	// field T1.AnotherMPSPS has no validation
	return errs
}
