//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package discriminated_union

import (
	fmt "fmt"

	validate "k8s.io/apimachinery/pkg/api/validate"
	runtime "k8s.io/apimachinery/pkg/runtime"
	field "k8s.io/apimachinery/pkg/util/validation/field"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *runtime.Scheme) error {
	scheme.AddValidationFunc((*DU)(nil), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_DU(obj.(*DU), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc((*T1)(nil), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_T1(obj.(*T1), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	return nil
}

var unionMembershipForDU = validate.NewDiscriminatedUnionMembership("d", [2]string{"m1", "M1"}, [2]string{"m2", "M2"})

func Validate_DU(obj *DU, fldPath *field.Path) (errs field.ErrorList) {
	// type DU
	if obj != nil {
		errs = append(errs, validate.DiscriminatedUnion(fldPath, *obj, unionMembershipForDU, obj.D, obj.M1, obj.M2)...)
	}

	// field DU.TypeMeta has no validation
	// field DU.D has no validation

	// field DU.M1
	errs = append(errs,
		func(obj *M1, fldPath *field.Path) (errs field.ErrorList) {
			if obj != nil {
				errs = append(errs, Validate_M1(obj, fldPath)...)
			}
			return
		}(obj.M1, fldPath.Child("m1"))...)

	// field DU.M2
	errs = append(errs,
		func(obj *M2, fldPath *field.Path) (errs field.ErrorList) {
			if obj != nil {
				errs = append(errs, Validate_M2(obj, fldPath)...)
			}
			return
		}(obj.M2, fldPath.Child("m2"))...)

	// field DU.T1
	errs = append(errs,
		func(obj *T1, fldPath *field.Path) (errs field.ErrorList) {
			if obj != nil {
				errs = append(errs, Validate_T1(obj, fldPath)...)
			}
			return
		}(obj.T1, fldPath.Child("t1"))...)

	return errs
}

func Validate_M1(obj *M1, fldPath *field.Path) (errs field.ErrorList) {
	// type M1
	if obj != nil {
		errs = append(errs, validate.FixedResult(fldPath, *obj, true, "type M1")...)
	}

	// field M1.S
	errs = append(errs,
		func(obj string, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field M1.S")...)
			return
		}(obj.S, fldPath.Child("s"))...)

	return errs
}

func Validate_M2(obj *M2, fldPath *field.Path) (errs field.ErrorList) {
	// type M2
	if obj != nil {
		errs = append(errs, validate.FixedResult(fldPath, *obj, true, "type M2")...)
	}

	// field M2.S
	errs = append(errs,
		func(obj string, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field M2.S")...)
			return
		}(obj.S, fldPath.Child("s"))...)

	return errs
}

func Validate_T1(obj *T1, fldPath *field.Path) (errs field.ErrorList) {
	// type T1
	if obj != nil {
		errs = append(errs, validate.FixedResult(fldPath, *obj, true, "type T1")...)
	}

	// field T1.TypeMeta has no validation

	// field T1.LS
	errs = append(errs,
		func(obj []string, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T1.LS")...)
			for i, val := range obj {
				errs = append(errs,
					func(obj string, fldPath *field.Path) (errs field.ErrorList) {
						if e := validate.Required(fldPath, obj); len(e) != 0 {
							errs = append(errs, e...)
							return // fatal
						}
						errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T1.LS[*]")...)
						return
					}(val, fldPath.Index(i))...)
			}
			return
		}(obj.LS, fldPath.Child("ls"))...)

	return errs
}
