//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package primitives

import (
	fmt "fmt"

	validate "k8s.io/apimachinery/pkg/api/validate"
	runtime "k8s.io/apimachinery/pkg/runtime"
	field "k8s.io/apimachinery/pkg/util/validation/field"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *runtime.Scheme) error {
	scheme.AddValidationFunc(new(T1), func(obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_T1(obj.(*T1), nil)
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	return nil
}

func Validate_T1(obj *T1, fldPath *field.Path) (errs field.ErrorList) {
	// field T1.TypeMeta has no validation

	// field T1.S
	errs = append(errs,
		func(obj string, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T1.S")...)
			return
		}(obj.S, fldPath.Child("s"))...)

	// field T1.I
	errs = append(errs,
		func(obj int, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T1.I")...)
			return
		}(obj.I, fldPath.Child("i"))...)

	// field T1.B
	errs = append(errs,
		func(obj bool, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T1.B")...)
			return
		}(obj.B, fldPath.Child("b"))...)

	// field T1.F
	errs = append(errs,
		func(obj float64, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T1.F")...)
			return
		}(obj.F, fldPath.Child("f"))...)

	// field T1.T2
	errs = append(errs,
		func(obj T2, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T1.T2")...)
			errs = append(errs, Validate_T2(&obj, fldPath)...)
			return
		}(obj.T2, fldPath.Child("t2"))...)

	// field T1.T3 has no validation
	// field T1.AnotherS has no validation
	// field T1.AnotherI has no validation
	// field T1.AnotherB has no validation
	// field T1.AnotherF has no validation

	// field T1.AnotherT2
	errs = append(errs,
		func(obj T2, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, Validate_T2(&obj, fldPath)...)
			return
		}(obj.AnotherT2, fldPath.Child("anothert2"))...)

	return errs
}

func Validate_T2(obj *T2, fldPath *field.Path) (errs field.ErrorList) {
	// field T2.S
	errs = append(errs,
		func(obj string, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T2.S")...)
			return
		}(obj.S, fldPath.Child("s"))...)

	// field T2.I
	errs = append(errs,
		func(obj int, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T2.I")...)
			return
		}(obj.I, fldPath.Child("i"))...)

	// field T2.B
	errs = append(errs,
		func(obj bool, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T2.B")...)
			return
		}(obj.B, fldPath.Child("b"))...)

	// field T2.F
	errs = append(errs,
		func(obj float64, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T2.F")...)
			return
		}(obj.F, fldPath.Child("f"))...)

	return errs
}

func Validate_T4(obj *T4, fldPath *field.Path) (errs field.ErrorList) {
	// field T4.S
	errs = append(errs,
		func(obj string, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T4.S")...)
			return
		}(obj.S, fldPath.Child("s"))...)

	// field T4.I
	errs = append(errs,
		func(obj int, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T4.I")...)
			return
		}(obj.I, fldPath.Child("i"))...)

	// field T4.B
	errs = append(errs,
		func(obj bool, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T4.B")...)
			return
		}(obj.B, fldPath.Child("b"))...)

	// field T4.F
	errs = append(errs,
		func(obj float64, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(fldPath, obj, true, "field T4.F")...)
			return
		}(obj.F, fldPath.Child("f"))...)

	return errs
}
